version: '6'
services:
  inventory-service:
    restart: always
    build: ./inventory-service
    ports:
      - "5002:5002"
    volumes:
      - /app/node_modules
      - ./inventory-service:/app

  shipping-service:
    restart: always # default is 'no', other values: always, on-failure and unless-stopped 
    build: ./shipping-service
    ports:
      - "5009:5009"
    volumes:
      - /app/node_modules
      - ./shipping-service:/app
    depends_on:
      - billing-service

  users-service:
    restart: always
    build: ./users-service
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./users-service:/app

  billing-service:
    restart: always
    build: ./billing-service
    ports:
      - "5001:5001"
    volumes:
      - /app/node_modules
      - ./billing-service:/app
